database:
  username: "admin"
  password: "andy12345"
  host: "mydatabase2.cn00ugsy224g.us-east-1.rds.amazonaws.com:3306"
  name: "mydatabase"

dynamodb:
  region: us-east-1
  endpoint: https://dynamodb.us-east-1.amazonaws.com
  access_key: ASIAW3MEBI4MSLZYPRZG
  secret_key: lkxelUzSS/n2qRu+VRi0+bjdNvN0CRHGLj/3Rtsh
  session_token: IQoJb3JpZ2luX2VjEO7//////////wEaCXVzLXdlc3QtMiJIMEYCIQDAfPFse/qCljXrL218cksp/ZzGuWO/JaXdTIOM4ghcmQIhAPijYmQ8y3KA9q3GSd25M8qn3KjkikSS7lZDbU5bDWd+KqwCCLf//////////wEQABoMNDcxMTEyNjk3NjI1IgwBQjhk/TajXbUjwS0qgAL2ZuYEwZZ6YaO7sDkameI32MOhbOJhDPSfk4lznLal4IcUxcW3IXWlJnH0Ym4xsKopSJ0pM7xhRWmDsP0SzeddyltQ679YR4VY3c47nJiy0x9g0hKX8JXBvVVP1U8GztSduepqzFnNkwcnOHZwIQ0xPMOXrPmcxx4RmW5uKgvbk4ViW96uaJCdONXC/TRAhFZOGi3LCaZxS7ZPKRgn9VqBcZzqgSfutcbBztdHXjQNr2lsfpnYBR/bBIEFMtgkxDAX6EjZfTIVIb3I9EbAeSYiyAilLfc+3bPN2HUtzqfW57QPAzTTJk6zGrnedVOKm2yrIACZ/iERDYHK082Sh+pYMKKn6sEGOpwBy39yEI0lBuuvNExq0/nPIr5wN6sFkthis5/M+u1yFyFjmWVcUYMxMwhSlM8anhMERhuiUnatF+rcXhcXhsBp8Y+UsgtOte1VyHjQlMdyod6neA7gzTQN/VQoz7vVmZdi4AA7uoUt/3770UenQNujBifQxMY2VTLmk2AV15SPK0iFrSJ4kVnX1NG186Jyhn1Iv5QGGen0kkdW/fFm


jwt:
  secret_key: "your-very-secret-key-for-jwt" # 強烈建議從環境變數讀取
  expiry_minutes: 60